// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Plant struct {
	ID        uuid.UUID
	Common    string
	Family    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Firstname string
	Lastname  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserPlant struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	PlantID   uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
