// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Plant struct {
	ID        uuid.UUID
	Common    string
	Family    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
