// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Plant struct {
	ID             uuid.UUID
	Common         string
	Family         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Latin          sql.NullString
	Category       sql.NullString
	Origin         sql.NullString
	Climate        sql.NullString
	Tempmax        sql.NullString
	Tempmin        sql.NullString
	Ideallight     sql.NullString
	Toleratedlight sql.NullString
	Watering       sql.NullString
	Insects        sql.NullString
	Diseases       sql.NullString
	Soil           sql.NullString
	Repotperiod    sql.NullString
	Use            sql.NullString
}

type User struct {
	ID        uuid.UUID
	Email     string
	Firstname string
	Lastname  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserPlant struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	PlantID   uuid.NullUUID
	CreatedAt time.Time
	UpdatedAt time.Time
}
