name: plantpal

services:
    database:
        image: postgres:14
        container_name: plantpal-database
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "6543:5432"

    plants-service:
        image: plants-service
        container_name: plants-service
        environment:
            DATABASE_URL: postgresql://postgres:password@0.0.0.0:6543/postgres?sslmode=disable
        build:
            context: .
            dockerfile: ./plants-service/Dockerfile
        ports:
            - "8001:8001"
            - "9001:9001"

    web-service:
        image: web-service
        container_name: web-service
        build:
            context: .
            dockerfile: ./web/Dockerfile
        ports:
            - "8000:8000"
