name: plantpal

services:
    plants-service:
        image: plants-service
        container_name: plants-service
        environment:
            DATABASE_URL: postgresql://postgres:password@0.0.0.0:6543/postgres?sslmode=disable
        build:
            context: ./plants-service
            dockerfile: ./Dockerfile
        ports:
            - "8001:8001"
            - "9001:9001"

    web-service:
        image: web-service
        container_name: web-service
        build:
            context: ./web
            dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
