// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: plants/plantspb/plants.proto

package plants

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlantsService_CreatePlant_FullMethodName = "/PlantsService/CreatePlant"
	PlantsService_GetPlants_FullMethodName   = "/PlantsService/GetPlants"
)

// PlantsServiceClient is the client API for PlantsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantsServiceClient interface {
	CreatePlant(ctx context.Context, in *CreatePlantRequest, opts ...grpc.CallOption) (*CreatePlantResponse, error)
	GetPlants(ctx context.Context, in *GetPlantsRequest, opts ...grpc.CallOption) (*GetPlantsResponse, error)
}

type plantsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantsServiceClient(cc grpc.ClientConnInterface) PlantsServiceClient {
	return &plantsServiceClient{cc}
}

func (c *plantsServiceClient) CreatePlant(ctx context.Context, in *CreatePlantRequest, opts ...grpc.CallOption) (*CreatePlantResponse, error) {
	out := new(CreatePlantResponse)
	err := c.cc.Invoke(ctx, PlantsService_CreatePlant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantsServiceClient) GetPlants(ctx context.Context, in *GetPlantsRequest, opts ...grpc.CallOption) (*GetPlantsResponse, error) {
	out := new(GetPlantsResponse)
	err := c.cc.Invoke(ctx, PlantsService_GetPlants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlantsServiceServer is the server API for PlantsService service.
// All implementations must embed UnimplementedPlantsServiceServer
// for forward compatibility
type PlantsServiceServer interface {
	CreatePlant(context.Context, *CreatePlantRequest) (*CreatePlantResponse, error)
	GetPlants(context.Context, *GetPlantsRequest) (*GetPlantsResponse, error)
	mustEmbedUnimplementedPlantsServiceServer()
}

// UnimplementedPlantsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlantsServiceServer struct {
}

func (UnimplementedPlantsServiceServer) CreatePlant(context.Context, *CreatePlantRequest) (*CreatePlantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlant not implemented")
}
func (UnimplementedPlantsServiceServer) GetPlants(context.Context, *GetPlantsRequest) (*GetPlantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlants not implemented")
}
func (UnimplementedPlantsServiceServer) mustEmbedUnimplementedPlantsServiceServer() {}

// UnsafePlantsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantsServiceServer will
// result in compilation errors.
type UnsafePlantsServiceServer interface {
	mustEmbedUnimplementedPlantsServiceServer()
}

func RegisterPlantsServiceServer(s grpc.ServiceRegistrar, srv PlantsServiceServer) {
	s.RegisterService(&PlantsService_ServiceDesc, srv)
}

func _PlantsService_CreatePlant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsServiceServer).CreatePlant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsService_CreatePlant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsServiceServer).CreatePlant(ctx, req.(*CreatePlantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantsService_GetPlants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsServiceServer).GetPlants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsService_GetPlants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsServiceServer).GetPlants(ctx, req.(*GetPlantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlantsService_ServiceDesc is the grpc.ServiceDesc for PlantsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlantsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PlantsService",
	HandlerType: (*PlantsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlant",
			Handler:    _PlantsService_CreatePlant_Handler,
		},
		{
			MethodName: "GetPlants",
			Handler:    _PlantsService_GetPlants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plants/plantspb/plants.proto",
}
