name: Fly Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build and push Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./lib/main
                  file: ./lib/main/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/domain-app:latest

    deploy:
        name: Deploy to Fly
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd ./lib/main && flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
