name: Fly Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build and deploy main
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./lib/main
                  file: ./lib/main/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/domain-app:latest

            - name: Deploy to Fly
              run: flyctl deploy --remote-only -a my-domain-app-muddy-haze-8196
