name: Domain App Pipeline
on:
    push:
        branches:
            - main
jobs:
    push_docker_image:
        name: Push Docker image to Dockerhub
        runs-on: ubuntu-latest
        needs: build_and_test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./lib/main
                  file: ./lib/main/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/domain-app:latest
                  build-args: |
                      "TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}"
                      "TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }}"
                      "MONGODB_URI=${{ secrets.MONGODB_URI }}"

    build_and_test:
        name: Build and run tests
        runs-on: ubuntu-latest
        env:
            TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
            TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22

            - name: Build
              run: cd ./lib/main && go build -o domain-app

            - name: Run tests
              run: cd ./lib/main && go test

    deploy:
        name: Deploy to Fly
        needs: push_docker_image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd ./lib/main && flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
                  TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
                  TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
