name: Fly Deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        env:
            TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
            TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
        name: Build and push Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5

              with:
                  context: ./lib/main
                  file: ./lib/main/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/domain-app:latest
                  TEST_DATABASE_URL: "$TEST_DATABASE_URL"
                  TURSO_AUTH_TOKEN: "$TURSO_AUTH_TOKEN"

    run_tests:
        name: Run tests
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run tests
              run: cd ./lib/main && go test

    test_db_connection:
        name: Test database connection
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: cd ./lib/main/db && go test

    deploy:
        name: Deploy to Fly
        needs: run_tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: cd ./lib/main && flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
