name: Plantpal Deployment Pipeline
on:
    push:
        branches:
            - main
jobs:
    push_docker_images:
        name: Push Docker images to Dockerhub
        runs-on: ubuntu-latest
        needs: build_and_test
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Plants Service
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./docker/plants-service/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/plantpal-plants-service:latest

            - name: Build and push Web App
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./docker/web/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/plantpal-web-app:latest

    build_and_test:
        name: Build and run tests
        runs-on: ubuntu-latest
        env:
            POSTGRES_URI: ${{ secrets.POSTGRES_URI }}

        steps:
            - uses: actions/checkout@v4
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.22
#            - name: Build
#              run: cd ./lib/main && go build -o domain-app
#
#            - name: Run tests
#              run: cd ./lib/main && go test
